# -*- coding: utf-8 -*-
"""JakartaKini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UkpyX4Afp8zAmzqQzcLpvJiLf8GE_HB4
"""

pip install google-play-scraper

from google_play_scraper import reviews, Sort
import csv
import pandas as pd
from transformers import pipeline

result, _ = reviews(
    'id.go.jakarta.smartcity.jaki',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=3000,
    filter_score_with=None
)

filename = 'ulasan_google_play.csv'


with open(filename, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=['userName', 'score', 'at', 'content'])
    writer.writeheader()
    for review in result:

        writer.writerow({
            'userName': review['userName'],
            'score': review['score'],
            'at': review['at'],
            'content': review['content']
        })

print(f"Berhasil menyimpan {len(result)} ulasan ke '{filename}'")

# Load the CSV into a pandas DataFrame
df = pd.read_csv(filename)

# Initialize the sentiment analysis pipeline using a pre-trained IndoRoberta model
# A common model for Indonesian sentiment analysis is 'w11wo/indonesian-roberta-base-sentiment-classifier'
sentiment_pipeline = pipeline("sentiment-analysis", model="w11wo/indonesian-roberta-base-sentiment-classifier")

# Perform sentiment analysis on the 'content' column
# This might take some time depending on the number of reviews
sentiment_results = sentiment_pipeline(df['content'].tolist())

# Extract sentiment label and score
df['sentiment_label'] = [res['label'] for res in sentiment_results]
df['sentiment_score'] = [res['score'] for res in sentiment_results]

# Display reviews with their sentiment analysis results
print("\nUlasan dengan Analisis Sentimen:")
print(df[['content', 'sentiment_label', 'sentiment_score']].head())

import matplotlib.pyplot as plt
import seaborn as sns

# Count the occurrences of each sentiment label
sentiment_counts = df['sentiment_label'].value_counts().reset_index()
sentiment_counts.columns = ['Sentiment', 'Count']

# Create a bar plot
plt.figure(figsize=(8, 6))
sns.barplot(x='Sentiment', y='Count', data=sentiment_counts, hue='Sentiment', palette='viridis', legend=False)
plt.title('Distribution of Sentiment Labels')
plt.xlabel('Sentiment')
plt.ylabel('Number of Reviews')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Save the DataFrame with sentiment analysis results to a new CSV file
df.to_csv('hasil_analisis_sentimen_JakartaKini.csv', index=False)
print("DataFrame saved to 'hasil_analisis_sentimen_JakartaKini.csv'")

# Display the first 5 rows of the DataFrame to confirm
print("\nFirst 3000 rows of the DataFrame with sentiment analysis:")
display(df.head())